# Generated by Django 5.1.2 on 2024-10-27 14:31

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcomProducts',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('galleries', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), size=6)),
                ('category_id', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
