# Generated by Django 5.1.2 on 2024-10-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecomproducts',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelTable(
            name='ecomproducts',
            table='ecom_products',
        ),
    ]
