# Generated by Django 5.1.2 on 2024-10-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_ecomproducts_options_alter_ecomproducts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.ecomcategory')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'ecom_category',
            },
        ),
        migrations.AlterField(
            model_name='ecomproducts',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.ecomcategory'),
        ),
    ]
