# Generated by Django 5.1.2 on 2024-10-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_ecomcategory_alter_ecomproducts_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, choices=[(0, 'XS'), (1, 'S'), (2, 'L'), (3, 'M'), (4, 'XL'), (5, 'XXl')], null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[(0, 'male'), (1, 'female'), (2, 'unisex')])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecomproducts')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'db_table': 'ecom_product_variant',
            },
        ),
    ]
