# Generated by Django 5.1.2 on 2024-10-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_ecomproductvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[(0, 'percentage'), (1, 'fixed')])),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'db_table': 'ecom_promotion',
            },
        ),
        migrations.CreateModel(
            name='EcomProductPromotionJoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecomproducts')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecompromotion')),
            ],
        ),
    ]
