# Generated by Django 5.1.2 on 2024-10-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_ecompromotion_ecomproductpromotionjointable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecomproductpromotionjointable',
            options={'verbose_name': 'Product Promotion Join Table', 'verbose_name_plural': 'Product Promotion Join Table'},
        ),
        migrations.AlterModelTable(
            name='ecomproductpromotionjointable',
            table='ecom_product_promotion_join_table',
        ),
    ]
