# Generated by Django 5.1.2 on 2024-10-29 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_ecomuserorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcomUserOrder',
            new_name='EcomCustomerOrder',
        ),
        migrations.AlterModelTable(
            name='ecomcustomerorder',
            table='ecom_customer_order',
        ),
    ]
