# Generated by Django 5.1.2 on 2024-10-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_ecomuserorder_ecomcustomerorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomPayment',
            fields=[
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerce.ecomcustomerorder')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[(0, 'cod'), (1, 'credit card'), (2, 'qr code'), (3, 'momo')])),
                ('payment_status', models.CharField(choices=[(0, 'pending'), (1, 'complete'), (2, 'failed')], default=0)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'ecom_customer_payment',
            },
        ),
    ]
