# Generated by Django 5.1.2 on 2024-10-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_ecompayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecomcustomerorder')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecomproductvariant')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'ecom_order_item',
            },
        ),
    ]
