# Generated by Django 5.1.2 on 2024-10-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_ecomproductreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('media_link', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'db_table': 'ecom_store',
            },
        ),
        migrations.CreateModel(
            name='EcomStoreBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ecomstore')),
            ],
            options={
                'verbose_name': 'store branch',
                'verbose_name_plural': 'store branches',
                'db_table': 'ecom_store_branch',
            },
        ),
    ]
