# Generated by Django 5.1.2 on 2024-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_ecomstore_ecomstorebranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomcategory',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
