# Generated by Django 5.1.2 on 2024-11-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_ecomcategory_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomcategory',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
