# Generated by Django 5.1.2 on 2024-11-13 04:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_ecomcategory_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomstore',
            name='banners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='ecomcategory',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='ecommerce.ecomcategory'),
        ),
    ]
