# Generated by Django 5.1.2 on 2024-11-13 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0016_ecomstore_logo_alter_ecomstore_media_link"),
    ]

    operations = []
    # migrations.AlterField(
    #     model_name='ecomstore',
    #     name='media_link',
    #     field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
    # ),
