# Generated by Django 5.1.2 on 2024-11-13 04:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_remove_ecomstore_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomstore',
            name='media_link',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
