# Generated by Django 5.1.2 on 2024-11-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_ecomstore_media_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecomstore',
            name='logo',
        ),
    ]
