# Generated by Django 5.1.2 on 2024-11-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_remove_ecomstore_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomstore',
            name='logo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
