# Generated by Django 5.1.2 on 2024-11-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_ecomstore_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('banner', models.CharField()),
                ('content', models.CharField()),
            ],
            options={
                'verbose_name': 'store guideline',
                'verbose_name_plural': 'store guideline',
                'db_table': 'ecom_store_guideline',
            },
        ),
        migrations.AddField(
            model_name='ecomstore',
            name='close_at',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='ecomstore',
            name='open_at',
            field=models.CharField(null=True),
        ),
    ]
