# Generated by Django 5.1.2 on 2024-11-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_storeguideline_ecomstore_close_at_ecomstore_open_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreGuideline',
            new_name='EcomStoreGuideline',
        ),
    ]
