# Generated by Django 5.1.2 on 2024-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0023_rename_storeguideline_ecomstoreguideline"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecomstoreguideline",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
