# Generated by Django 5.1.2 on 2024-11-18 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0024_ecomstoreguideline_slug"),
    ]

    operations = []
    # migrations.RemoveField(
    #     model_name='ecomstoreguideline',
    #     name='slug',
    # ),
