# Generated by Django 5.1.2 on 2024-11-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_remove_ecomstoreguideline_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomstoreguideline',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
