# Generated by Django 5.1.2 on 2024-11-19 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_ecomstoreguideline_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomproducts',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='ecomproductvariant',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.ecomproducts'),
        ),
    ]
