# Generated by Django 5.1.2 on 2024-11-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_rename_category_id_ecomproducts_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomcategory',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
