# Generated by Django 5.1.2 on 2024-11-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_rename_parent_id_ecomcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomstorebranch',
            old_name='store_id',
            new_name='store',
        ),
    ]
