# Generated by Django 5.1.2 on 2024-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_ecompromotion_can_stack_ecompromotion_link_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecompromotion',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
