# Generated by Django 5.1.2 on 2024-11-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_ecompromotion_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecompromotion',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='ecompromotion',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='ecompromotion',
            name='min_purchase',
        ),
        migrations.AlterField(
            model_name='ecompromotion',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EcomPromotionDiscountVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_item', models.PositiveSmallIntegerField(default=0)),
                ('max_item', models.PositiveSmallIntegerField(default=0)),
                ('min_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(choices=[(0, '%'), (1, 'k')])),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_variant', to='ecommerce.ecompromotion')),
            ],
            options={
                'verbose_name': 'promotion discount variant',
                'verbose_name_plural': 'promotion discount variants',
                'db_table': 'ecom_promotion_discount_variant',
            },
        ),
    ]
