# Generated by Django 5.1.2 on 2024-11-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0032_remove_ecompromotion_discount_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecompromotiondiscountvariant",
            name="promo",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="ecommerce.ecompromotion",
            ),
            preserve_default=False,
        ),
    ]
