# Generated by Django 5.1.2 on 2024-11-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_ecompromotiondiscountvariant_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecompromotiondiscountvariant',
            name='promotion',
        ),
    ]
