# Generated by Django 5.1.2 on 2024-11-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_remove_ecompromotiondiscountvariant_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecompromotiondiscountvariant',
            name='promo',
        ),
        migrations.AddField(
            model_name='ecompromotiondiscountvariant',
            name='promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_variant', to='ecommerce.ecompromotion'),
        ),
    ]
