# Generated by Django 5.1.2 on 2024-11-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_rename_ecomproductpromotionjointable_ecomproductpromotionextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomproducts',
            name='promotions',
            field=models.ManyToManyField(through='ecommerce.EcomProductPromotionExtra', to='ecommerce.ecompromotion'),
        ),
    ]
