# Generated by Django 5.1.2 on 2024-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_ecomproducts_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproducts',
            name='promotions',
            field=models.ManyToManyField(related_name='products', through='ecommerce.EcomProductPromotionExtra', to='ecommerce.ecompromotion'),
        ),
        migrations.AddIndex(
            model_name='ecomproducts',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['slug'], name='product_slug_idx'),
        ),
    ]
