# Generated by Django 5.1.2 on 2024-12-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_alter_ecomproducts_promotions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomproductvariant',
            old_name='product_id',
            new_name='product',
        ),
    ]
