# Generated by Django 5.1.2 on 2024-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_rename_product_id_ecomproductvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproducts',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ecomproductvariant',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXl')], null=True),
        ),
    ]
