# Generated by Django 5.1.2 on 2024-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_alter_ecomproducts_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomproductvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
