# Generated by Django 5.1.2 on 2024-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_ecomproductvariant_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomproductvariant',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'unisex')]),
        ),
    ]
