# Generated by Django 5.1.2 on 2024-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
