# Generated by Django 5.1.2 on 2024-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ecomuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
